### ISSUE TITLE
Hunt for O365/Exchange Business Email Compromise (BEC)

### ISSUE THREAD

**Issue by rhigham-scwx** [rhigham-scwx/ben-alder-4#3]
**Title:** Hunt for O365 Business Email Compromise (BEC) 
**Hypothesis:** Threat Actors have gained access to one of more mailboxes and are using them to conduct transactions or exfiltrate sensitive information  
**Trigger:** Threat Actor Intelligence 
**Reference:**
- https://www.sans.org/blog/sans-data-incident-2020-indicators-of-compromise/
- https://attack.mitre.org/techniques/T1114/003/
- https://attack.mitre.org/techniques/T1114/002/

**Acceptance Criteria**  
This issue can be closed when the abstract has been updated and the report has been written. If the hunt can not be completed, this issue should be marked as blocked. If the issue is no longer needed, it should be labeled as such and then closed.

**Tasks**
- [x] Validate Security Gap Exists
- [x] Validate Data Visibility/Usability
- [x] Define/Refine Playbook
- [x] Gather and Analyze Data (According to the Playbook)
- [x] Update the Abstract
- [x] Write Report
- [x] Share Findings
- [x] Close Issue
- [x] Create New Issue (if needed)

**Note:** 
- Incidents should be escalated as they are found.
- If you plan to test the security gap exists through adversary emulation, notify your manager and security operations.
- If you find inappropriate content or other compliance issues, check with management to determine next steps.
- If this hunt did not produce logic that can be used to address the known gap, open a new issue to repeat the hunt in the future.
