### ISSUE TITLE
<hunt_name>

### ISSUE THREAD

**Issue by rhigham-scwx** [rhigham-scwx/ben-alder-4#6]
**Title:** Hunt for xyz  
**Hypothesis:** Adversaries are using PowerShell to perform malicious actions such as discovery of information and execution of code.
**Trigger:** Threat Actor Intel
**Reference:** 
- https://blog.trendmicro.com/trendlabs-security-intelligence/muddywater-resurfaces-uses-multi-stage-backdoor-powerstats-v3-and-new-post-exploitation-tools/

**Acceptance Criteria**  
This issue can be closed when the abstract has been updated and the report has been written. If the hunt can not be completed, this issue should be marked as blocked. If the hunt is no longer needed, the issue should be labeled as such and then closed.

**Tasks**
- [ ] Validate Security Gap Exists
- [ ] Validate Data Visibility/Usability
- [ ] Define/Refine Abstract
- [ ] Gather and Analyze Data (According to the Playbook)
- [ ] Update the Abstract
- [ ] Write Report
- [ ] Share Findings
- [ ] Close Issue
- [ ] Create New Issue (if needed)

**Note:** 
- Incidents should be escalated as they are found.
- If you plan to test the security gap exists through adversary emulation, notify your manager and security operations.
- If you find inappropriate content or other compliance issues, check with management to determine next steps.
- If this hunt did not produce logic that can be used to address the known gap, open a new issue to repeat the hunt in the future.
